### ISSUE TITLE
homepage prices not update to DB

### ISSUE THREAD

**Issue by othmaneihiri** [yusuf-mutlu/crypto-coin-portfolio-tracker#1]
Hello my friend i just installed this project in my dev env but 
![image](https://user-images.githubusercontent.com/63060495/184545834-d3576829-3335-45b4-9a20-be781d25ed67.png)

**Comment by yusuf-mutlu** [comment]
It looks Coingecko updated their API rate limit policy. I sent an update to fix it and  it should be okay.
[see the commit](https://github.com/yusuf-mutlu/crypto-coin-portfolio-tracker/commit/c545d6ac3d65ee463b47bbef2cc4cf91d542be60)
