### ISSUE TITLE
get call error

### ISSUE THREAD

**Issue by othmaneihiri** [yusuf-mutlu/crypto-coin-portfolio-tracker#2]
Hello sir , here is another error in get call 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/63060495/185391759-47625de4-2976-49d4-bea6-205db6b7dfbf.png">

**Comment by yusuf-mutlu** [comment]
You must set your APP_URL in your .env file

example:

`APP_URL=http://127.0.0.1:8000`
