### ISSUE TITLE
schle work without update !!!

### ISSUE THREAD

**Issue by othmaneihiri** [yusuf-mutlu/crypto-coin-portfolio-tracker#4]
When I execute this command php artisan schedule:work , i got this result without any update on database :
<img width="543" alt="image" src="https://user-images.githubusercontent.com/63060495/185748916-d8b19a5d-7e0a-471a-85a3-55562368a469.png">
 

I search in the code I found that when I execute the update of the prices with this command : php artisan coinGecko:saveCoinPrices   I got the same error of 'rate limit' 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/63060495/185749412-c5f44f52-5e76-411b-8ce5-590505c2dbd8.png">

**Comment by mouadaqma** [comment]
Yeah I have the same error too ... I think you should increase rate limit to the max

**Comment by yusuf-mutlu** [comment]
Can you pull the latest code and try again? 

It takes more than 3 minutes to update coin prices data. I set the update interval to 5 minutes in schedule service. I assume you shouldn't get an error. Also please be careful, don't run `php artisan coinGecko:saveCoinPrices` command separately when schedule is working. It may cause the rate limit issue.

**Comment by mouadaqma** [comment]
The problem is the free coingeko api !

**Comment by othmaneihiri** [comment]
> Can you pull the latest code and try again?
> 
> It takes more than 3 minutes to update coin prices data. I set the update interval to 5 minutes in schedule service. I assume you shouldn't get an error. Also please be careful, don't run `php artisan coinGecko:saveCoinPrices` command separately when schedule is working. It may cause the rate limit issue.

I think it's Okey bro thanks .
